credentials:
  usernames:
    admin:
      name: 管理者
      password: "$2b$12$TFFOhw0Vc43djCueULCQJeH6LCoG3X/X.N0VGDWoyTKQZj3KMKykS"

cookie:
  name: insurance_auth
  key: random_cookie_key_123
  expiry_days: 1
